#!/usr/bin/env node
/** T-2060. Derive renderers/web/js/boot-weights.js from committed receipts.
 *
 * The weights pace a first visit's arrival in seconds, and they were read on one
 * reference machine (tools/boot_phase_measurements.json, the T-1246 receipt). A run
 * reaches only a software-WebGL runner, 2-7x slower phase by phase. So the runner is
 * not asked how long the boot takes; it is asked how much each phase GREW. It measures
 * the reference reading's own tree and today's tree on the same machine, and each
 * weight is the reference reading times that phase's growth in that cell:
 *
 *   weight[cell][phase] = reference[cell][phase] x today[cell][phase] / then[cell][phase]
 *
 * A phase today's boot no longer runs keeps its reference reading (the test requires
 * every cell positive; an optional phase paces nothing).
 *
 *   --write THEN.json TODAY.json   compact both `measure_boot_phases.mjs --json`
 *                                  outputs into tools/boot_weights_calibration.json
 *                                  and regenerate boot-weights.js from it
 *   --check                        re-derive boot-weights.js from the committed
 *                                  receipts and fail if the file differs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const REFERENCE = path.join(here, 'boot_phase_measurements.json');
const RECEIPT = path.join(here, 'boot_weights_calibration.json');
const OUT = path.join(here, '../renderers/web/js/boot-weights.js');
const PHASES = ['scene', 'terrain', 'buildings', 'ground', 'flora', 'people', 'census', 'interaction'];
const cellKey = r => `${r.device}/${r.detail}/${r.cache}`;
const round = n => Math.round(n * 1e4) / 1e4;

function compact(doc, tree) {
  return {
    tree, measuredAt: doc.measuredAt, machine: doc.machine, browser: doc.browser,
    conditions: doc.conditions,
    cells: Object.fromEntries(doc.rows.map(r => [cellKey(r), {
      readySeconds: round(r.readyAt / 1000),
      phases: Object.fromEntries(PHASES.map(id => {
        const s = r.phases.find(p => p.id === id)?.seconds;
        return [id, Number.isFinite(s) ? round(s) : null];
      })),
    }])),
  };
}

export function derive(reference, receipt) {
  const weights = {};
  for (const row of reference.rows) {
    const key = cellKey(row), then = receipt.then.cells[key]?.phases, now = receipt.today.cells[key]?.phases;
    if (!then || !now) throw new Error(`calibration receipt has no ${key} cell`);
    const cell = {};
    for (const id of PHASES) {
      const ref = row.phasesSeconds[id];
      cell[id] = round(Number.isFinite(now[id]) && then[id] > 0 ? ref * now[id] / then[id] : ref);
    }
    ((weights[row.device] ??= {})[row.detail] ??= {})[row.cache] = cell;
  }
  return weights;
}

export function render(reference, receipt) {
  return [
    `// T-2060 calibrated ${receipt.today.measuredAt}: the T-1246 reference reading`,
    `// (${reference.machine}; Chromium ${reference.browser}; ${reference.measuredAt})`,
    `// times each phase's growth from tree ${receipt.then.tree} to ${receipt.today.tree}, both read on`,
    `// ${receipt.today.machine}; Chromium ${receipt.today.browser}.`,
    `// ${reference.conditions}`,
    '// Receipts: tools/boot_phase_measurements.json + tools/boot_weights_calibration.json.',
    '// Generated by tools/calibrate_boot_weights.mjs; never hand-edit. Seconds, not percentages.',
    `export const BOOT_WEIGHTS = ${JSON.stringify(derive(reference, receipt), null, 2)};`,
    '',
  ].join('\n');
}

const args = process.argv.slice(2);
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const reference = JSON.parse(fs.readFileSync(REFERENCE, 'utf8'));
  if (args[0] === '--write') {
    const [thenFile, todayFile] = args.slice(1);
    const read = f => JSON.parse(fs.readFileSync(f, 'utf8'));
    const tree = flag => args.includes(flag) ? args[args.indexOf(flag) + 1] : 'unrecorded';
    const receipt = {
      ticket: 'T-2060',
      method: 'weight = reference x (today / then) per cell and phase; then and today read on one machine',
      then: compact(read(thenFile), tree('--then-tree')),
      today: compact(read(todayFile), tree('--today-tree')),
    };
    fs.writeFileSync(RECEIPT, JSON.stringify(receipt, null, 1) + '\n');
    fs.writeFileSync(OUT, render(reference, receipt));
    console.log(`wrote ${path.relative(process.cwd(), RECEIPT)} and ${path.relative(process.cwd(), OUT)}`);
  } else if (args[0] === '--check') {
    const receipt = JSON.parse(fs.readFileSync(RECEIPT, 'utf8'));
    const want = render(reference, receipt), have = fs.readFileSync(OUT, 'utf8');
    if (want !== have) {
      console.error('boot-weights.js does not re-derive from its receipts: run tools/calibrate_boot_weights.mjs --write, never hand-edit it');
      process.exit(1);
    }
    console.log('boot weights PASS: boot-weights.js re-derives from the reference reading and the calibration receipt');
  } else {
    console.error('usage: calibrate_boot_weights.mjs --write THEN.json TODAY.json [--then-tree SHA] [--today-tree SHA] | --check');
    process.exit(2);
  }
}
