// T-2060 calibrated 2026-10-08T07:03:20.976Z: the T-1246 reference reading
// (Darwin 25.6.0 arm64 / Apple M5 Max; Chromium 153.0.8010.12; 2026-09-20T18:27:46.533Z)
// times each phase's growth from tree custom@e53e46c3b to 1ab737cb4, both read on
// Linux 6.17.0-1022-azure x64 / AMD EPYC 7763 64-Core Processor; Chromium 156.0.8078.4.
// Headless Chromium; 390×780 touch and 1280×800; no CPU throttle; fresh context cold, repeat navigation warm.
// Receipts: tools/boot_phase_measurements.json + tools/boot_weights_calibration.json.
// Generated by tools/calibrate_boot_weights.mjs; never hand-edit. Seconds, not percentages.
export const BOOT_WEIGHTS = {
  "mobile": {
    "light": {
      "cold": {
        "scene": 0.3539,
        "terrain": 1.1818,
        "buildings": 0.2135,
        "ground": 0.9633,
        "flora": 1.2068,
        "people": 0.0931,
        "census": 0.0044,
        "interaction": 1.3399
      },
      "warm": {
        "scene": 0.2965,
        "terrain": 0.6859,
        "buildings": 0.0581,
        "ground": 0.4124,
        "flora": 2.6825,
        "people": 0.0803,
        "census": 0.0226,
        "interaction": 1.2723
      }
    },
    "balanced": {
      "cold": {
        "scene": 0.314,
        "terrain": 1.2188,
        "buildings": 0.2214,
        "ground": 1.1579,
        "flora": 2.2394,
        "people": 0.103,
        "census": 0.0059,
        "interaction": 2.043
      },
      "warm": {
        "scene": 0.2741,
        "terrain": 0.6105,
        "buildings": 0.0597,
        "ground": 0.4999,
        "flora": 3.5832,
        "people": 0.084,
        "census": 0.0028,
        "interaction": 1.3763
      }
    },
    "full": {
      "cold": {
        "scene": 0.3272,
        "terrain": 1.2296,
        "buildings": 0.1651,
        "ground": 1.0934,
        "flora": 3.0285,
        "people": 0.0997,
        "census": 0.0037,
        "interaction": 2.0481
      },
      "warm": {
        "scene": 0.4068,
        "terrain": 0.6462,
        "buildings": 0.0596,
        "ground": 0.4552,
        "flora": 4.6824,
        "people": 0.0763,
        "census": 0.0236,
        "interaction": 1.3658
      }
    }
  },
  "desktop": {
    "light": {
      "cold": {
        "scene": 0.31,
        "terrain": 1.1933,
        "buildings": 0.2468,
        "ground": 0.895,
        "flora": 1.3128,
        "people": 0.0908,
        "census": 0.0032,
        "interaction": 2.3088
      },
      "warm": {
        "scene": 0.3322,
        "terrain": 1.1265,
        "buildings": 0.1714,
        "ground": 0.7718,
        "flora": 1.7803,
        "people": 0.0882,
        "census": 0.0046,
        "interaction": 1.7063
      }
    },
    "balanced": {
      "cold": {
        "scene": 0.2717,
        "terrain": 1.1704,
        "buildings": 0.1382,
        "ground": 1.1187,
        "flora": 1.9092,
        "people": 0.1043,
        "census": 0.0034,
        "interaction": 2.4642
      },
      "warm": {
        "scene": 0.3019,
        "terrain": 1.0642,
        "buildings": 0.1697,
        "ground": 0.8391,
        "flora": 2.5197,
        "people": 0.0878,
        "census": 0.0045,
        "interaction": 1.6267
      }
    },
    "full": {
      "cold": {
        "scene": 0.2799,
        "terrain": 1.1515,
        "buildings": 0.1494,
        "ground": 1.0838,
        "flora": 2.353,
        "people": 0.0965,
        "census": 0.0038,
        "interaction": 2.4972
      },
      "warm": {
        "scene": 0.288,
        "terrain": 1.2026,
        "buildings": 0.1786,
        "ground": 0.8305,
        "flora": 3.3475,
        "people": 0.0967,
        "census": 0.0045,
        "interaction": 1.6746
      }
    }
  }
};
