/**
 * street-grid.js — the 1904 Prairie Avenue street, alley and parcel grid (T-0474),
 * draped on the scene's own heightfield.
 *
 * WHAT IT DRAWS, from `data/street_grid/<scene>.json` (generated by
 * tools/trace_prairie_1904_grid.py from the Sanborn 1911 sheets 20, 28 and 35):
 *
 *   carriageways   curb line to curb line, one polygon per street segment
 *   faces          the four bands of every block's sidewalk space, measured from
 *                  the street line: a 1-ft margin, the walk, the parkway, the curb
 *   alleys         at their drawn widths
 *   parcels        as lines: the lots on both faces of Prairie Avenue
 *
 * WHAT IT DOES NOT CLAIM. No material. Every surface is a flat neutral tone chosen
 * only so the bands can be told apart — the paving, the curb's stone or timber, the
 * walk's plank, stone or cement, and the parkway's grass are T-1728's to source, and
 * nothing here is a reading of any of them. Nor any level: the bands lie on the
 * ground the heightfield already has (a few centimetres above it, so they win the
 * depth test), with no curb reveal and no crown, because no source read so far gives
 * either (docs/LIBERTIES.md L291).
 *
 * WHAT IT SHARES WITH EVERY OTHER DERIVED LAYER. A scene that does not list
 * `street_grid` hands this no data base and it draws nothing (T-1739's layer
 * contract), so the 1835 town is untouched. A failed fetch degrades to nothing
 * drawn plus a recorded problem, never to an invented street. Every vertex carries
 * `_confidence` at its band's tier, so hiding `reconstructed` takes the walk, the
 * parkway and the curb away and leaves the inferred carriageway and street lines.
 * A pick opens a card built from the grid's own record: the parcel with its 1911
 * addresses and the sheet it was read from, or the band with its width and tier.
 */

import * as THREE from 'three';

/** Longest triangle edge after draping, metres. The heightfield's cell is 2.5 m,
 *  so a triangle no longer than that cannot bridge a cell and float or sink. */
const MAX_EDGE_M = 2.5;
const LEVEL = { attested: 0, inferred: 0.5, reconstructed: 1 };

/**
 * The draw order is the stacking order: each class a few centimetres above the one
 * it overlaps, plus a polygon offset, so a band laid over a carriageway (the
 * carriageways run through their intersections and under the corner bands) always
 * wins. Tones are neutral placeholders, not materials — see the header.
 */
const CLASSES = {
  carriageway: { lift: 0.03, colour: 0x7a7066, offset: -8, tier: 'inferred' },
  alley: { lift: 0.035, colour: 0x857a6c, offset: -9, tier: 'inferred' },
  margin: { lift: 0.05, colour: 0x7c8a66, offset: -10, tier: 'inferred' },
  parkway: { lift: 0.05, colour: 0x7c8a66, offset: -10, tier: 'reconstructed' },
  walk: { lift: 0.055, colour: 0xc2bdb2, offset: -11, tier: 'reconstructed' },
  curb: { lift: 0.06, colour: 0xd9d5cc, offset: -12, tier: 'reconstructed' },
};
const LOT_LINE_LIFT_M = 0.09;
const LOT_LINE_STEP_M = 2.0;

const wx = (e) => e;
const wz = (n) => -n;

async function getJSON(url) {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.json();
}

/**
 * A quad (a, b along one side, d, c along the other) to plan triangles on a grid
 * no coarser than MAX_EDGE_M in either direction, by bilinear interpolation. Every
 * surface in the grid file is a list of such quads -- a band of a block face, a
 * straight carriageway or alley (one quad), or a curved one (one quad every 5 m) --
 * so a strip 15 cm wide costs two triangles per 2.5 m of its length, not the
 * hundreds an isotropic subdivision spends on a sliver.
 */
function quadTriangles(q) {
  let [a, b, c, d] = q;
  const cross = (b[0] - a[0]) * (d[1] - a[1]) - (b[1] - a[1]) * (d[0] - a[0]);
  if (cross < 0) [b, d] = [d, b];   // counter-clockwise in plan, so normals point up
  const along = Math.max(Math.hypot(b[0] - a[0], b[1] - a[1]), Math.hypot(c[0] - d[0], c[1] - d[1]));
  const across = Math.max(Math.hypot(d[0] - a[0], d[1] - a[1]), Math.hypot(c[0] - b[0], c[1] - b[1]));
  const nu = Math.max(1, Math.ceil(along / MAX_EDGE_M));
  const nv = Math.max(1, Math.ceil(across / MAX_EDGE_M));
  const at = (u, v) => {
    const e0 = a[0] + (b[0] - a[0]) * u; const n0 = a[1] + (b[1] - a[1]) * u;
    const e1 = d[0] + (c[0] - d[0]) * u; const n1 = d[1] + (c[1] - d[1]) * u;
    return [e0 + (e1 - e0) * v, n0 + (n1 - n0) * v];
  };
  const out = [];
  for (let i = 0; i < nu; i += 1) {
    for (let j = 0; j < nv; j += 1) {
      const p00 = at(i / nu, j / nv); const p10 = at((i + 1) / nu, j / nv);
      const p11 = at((i + 1) / nu, (j + 1) / nv); const p01 = at(i / nu, (j + 1) / nv);
      out.push([p00, p10, p11], [p00, p11, p01]);
    }
  }
  return out;
}

function pointInPolygon(e, n, poly) {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i, i += 1) {
    const [xi, yi] = poly[i]; const [xj, yj] = poly[j];
    if ((yi > n) !== (yj > n) && e < ((xj - xi) * (n - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

function ftm(ft) { return `${ft} ft (${(ft * 0.3048).toFixed(2)} m)`; }

/* -------------------------------------------------------------------------- */
/* the cards                                                                   */
/* -------------------------------------------------------------------------- */

function parcelCard(p, grid) {
  const sheet = (p.sources ?? [])[0] ?? '';
  const addr = p.addresses_1911?.length ? p.addresses_1911.join(', ') : null;
  const ruling = p.id === grid.rulings?.glessner_lot_frontage?.parcel ? grid.rulings.glessner_lot_frontage : null;
  const attributes = {
    frontage_ft: {
      value: p.frontage_ft, confidence: ruling ? ruling.tier : p.geometry_tier,
      sources: ruling ? ruling.sources : p.sources,
      note: ruling ? `${ruling.reading} ${ruling.why_not_77} ${ruling.why_not_74}` : p.read,
    },
    depth_ft: { value: p.depth_ft, confidence: p.geometry_tier, sources: p.sources, note: p.read },
    addresses_printed_1911: {
      value: addr ?? 'none printed', confidence: 'inferred', sources: [sheet],
      note: 'The numbers the 1911 sheet prints beside this lot. Chicago renumbered its streets in 1909-11, '
        + 'so a 1911 number is a cross-reference to the Prairie library, not a claim about the 1904 address'
        + (p.library_disagreements?.length ? `. ${p.library_disagreements.map((d) => d.reading).join(' ')}` : '.'),
    },
    street_face: { value: p.street_face, confidence: 'inferred', sources: p.sources, note: 'The block face this lot fronts, as laid out in the grid.' },
  };
  return {
    id: p.id,
    sidecar: {
      name: addr ? `${p.addresses_1911[0].split(' ')[0]} Prairie Avenue — the lot` : 'A lot on Prairie Avenue',
      phase: null,
      placement: {
        symbolic_location: `${p.side === 'west' ? 'West' : 'East'} side of Prairie Avenue, block ${p.block.replace('blk_', '').replace(/_/g, ' ')}`,
        position_confidence: p.geometry_tier,
        position_sources: p.sources,
        position_note: `${p.read}. A 1911 survey carried to 1904: the lot lines are assumed unchanged between the two dates.`,
      },
      attributes,
      citations: [],
      research_doc: 'docs/RESEARCH/prairie_1904_street_grid.md',
      research_note: `Parcel ${p.id} of the 1904 Prairie Avenue grid (data/street_grid/1904.json, T-0474)`
        + (p.library_frontage_ids?.length ? `; the Prairie library's frontage rows ${p.library_frontage_ids.join(', ')}` : '')
        + '. No building is drawn on it yet.'
        + (ruling ? ` ${ruling.for_T_1732 ?? ruling['for_T-1732'] ?? ''}` : ''),
    },
  };
}

function bandCard(face, band, grid) {
  const street = grid.streets?.[face.street] ?? {};
  const xs = grid.cross_sections?.[face.cross_section] ?? {};
  const b = (xs.bands ?? []).find((x) => x.band === band) ?? {};
  const words = { margin: 'the margin inside the walk', walk: 'the walk', parkway: 'the parkway', curb: 'the curb' };
  return {
    id: `${face.id}.${band}`,
    sidecar: {
      name: `${street.name_1904 ?? face.street} — ${words[band] ?? band}`,
      phase: null,
      placement: {
        symbolic_location: `Beside block ${face.block.replace('blk_', '').replace(/_/g, ' ')}`,
        position_confidence: face.street_line_tier === 'derived' ? 'inferred' : 'inferred',
        position_sources: grid.sources ?? [],
        position_note: `Measured from the street line read off ${face.street_line_from}.`,
      },
      attributes: {
        width: {
          value: ftm(Math.round((b.to_ft - b.from_ft) * 10) / 10), confidence: b.tier ?? 'reconstructed',
          sources: b.sources ?? [], note: b.note ?? '',
        },
        from_street_line: {
          value: `${b.from_ft} to ${b.to_ft} ft`, confidence: b.tier ?? 'reconstructed', sources: b.sources ?? [],
          note: 'Measured outward from the street (property) line into the street.',
        },
        sidewalk_space: {
          value: ftm(xs.sidewalk_space_ft?.value), confidence: xs.sidewalk_space_ft?.tier ?? 'inferred',
          sources: xs.sidewalk_space_ft?.sources ?? [], note: xs.sidewalk_space_ft?.note ?? '',
        },
        material: {
          value: 'not claimed', confidence: 'reconstructed', sources: [],
          note: 'Drawn in a neutral tone. What it was made of is T-1728’s to source.',
        },
      },
      citations: [],
      research_doc: 'docs/RESEARCH/prairie_1904_street_grid.md',
      research_note: `Street face ${face.id} of the 1904 Prairie Avenue grid (T-0474). ${street.width_note ?? ''}`,
    },
  };
}

function wayCard(kind, rec, grid) {
  const street = kind === 'carriageway' ? grid.streets?.[rec.street] ?? {} : {};
  const xs = grid.cross_sections?.[street.cross_section] ?? {};
  const attributes = kind === 'carriageway' ? {
    street_width: { value: ftm(street.row_width_ft), confidence: street.row_width_tier ?? 'inferred', sources: street.row_width_sources ?? [], note: street.width_note ?? '' },
    carriageway: {
      value: ftm(street.row_width_ft - 2 * (xs.sidewalk_space_ft?.value ?? 0)), confidence: 'inferred',
      sources: rec.sources ?? [], note: `The street width less a ${xs.sidewalk_space_ft?.value}-ft sidewalk space on each side. ${xs.sidewalk_space_ft?.note ?? ''}`,
    },
    paving: { value: 'not claimed', confidence: 'reconstructed', sources: [], note: 'Drawn in a neutral tone; T-1728 owns the surface.' },
  } : {
    width: { value: `${rec.printed_width_ft} ft as printed`, confidence: 'inferred', sources: rec.sources ?? [], note: rec.note ?? 'Drawn at the width the sheet draws.' },
    surface: { value: 'not claimed', confidence: 'reconstructed', sources: [], note: 'Drawn in a neutral tone; T-1728 owns the surface.' },
  };
  return {
    id: rec.id,
    sidecar: {
      name: kind === 'carriageway' ? `${street.name_1904 ?? rec.street} — the roadway` : 'An alley',
      phase: null,
      placement: {
        symbolic_location: kind === 'carriageway' ? (street.printed ? `Printed "${street.printed}" on the 1911 sheets` : '') : `Behind the lots of ${rec.block.replace('blk_', '').replace(/_/g, ' ')}`,
        position_confidence: rec.geometry_tier ?? 'inferred',
        position_sources: rec.sources ?? [],
        position_note: `Between ${(rec.between ?? rec.drawn_from ?? []).join(' and ')}.`,
      },
      attributes,
      citations: [],
      research_doc: 'docs/RESEARCH/prairie_1904_street_grid.md',
      research_note: `${kind === 'carriageway' ? 'Carriageway' : 'Alley'} ${rec.id} of the 1904 Prairie Avenue grid (T-0474).`,
    },
  };
}

/* -------------------------------------------------------------------------- */
/* the layer                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * @param {object} o dataBase (data/ root, or null when the scene does not list the
 *                   layer) · sceneId · terrain · confidence · problems
 */
export async function createStreetGrid({
  dataBase, sceneId, terrain, confidence = null, problems = [],
} = {}) {
  const group = new THREE.Group();
  group.name = 'street-grid';
  const out = {
    group,
    grid: null,
    census: { carriageways: 0, faces: 0, alleys: 0, parcels: 0, triangles: 0 },
    parcelAt: () => null,
    pickAt: () => null,
    dispose: () => {},
  };
  if (!dataBase || !terrain) return out;
  let grid;
  try {
    grid = await getJSON(new URL(`street_grid/${sceneId}.json`, dataBase));
  } catch (err) {
    problems.push(`street grid: ${err.message} — no street is drawn`);
    return out;
  }
  out.grid = grid;

  const bufs = {};
  const spans = {};
  const push = (cls, id, quads, tier) => {
    const c = CLASSES[cls];
    const level = LEVEL[tier ?? c.tier] ?? 1;
    const buf = (bufs[cls] ??= { pos: [], conf: [] });
    const from = buf.pos.length / 9;
    for (const q of quads) {
      for (const tri of quadTriangles(q)) {
        for (const [e, n] of tri) {
          buf.pos.push(wx(e), terrain.surfaceHeight(e, n) + c.lift, wz(n));
          buf.conf.push(level);
        }
      }
    }
    (spans[cls] ??= []).push({ id, from, to: buf.pos.length / 9 });
  };

  for (const c of grid.carriageways ?? []) { push('carriageway', c.id, c.quads_local_m ?? [], c.geometry_tier); out.census.carriageways += 1; }
  for (const a of grid.alleys ?? []) { push('alley', a.id, a.quads_local_m ?? [], a.geometry_tier); out.census.alleys += 1; }
  const tierOf = {};
  for (const xs of Object.values(grid.cross_sections ?? {})) for (const b of xs.bands ?? []) tierOf[b.band] = b.tier;
  for (const f of grid.faces ?? []) {
    for (const [band, quads] of Object.entries(f.bands ?? {})) {
      if (!CLASSES[band]) continue;
      push(band, `${f.id}|${band}`, quads, tierOf[band]);
    }
    out.census.faces += 1;
  }

  const meshes = [];
  const materials = [];
  for (const [cls, buf] of Object.entries(bufs)) {
    const c = CLASSES[cls];
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(buf.pos, 3));
    geo.setAttribute('_confidence', new THREE.Float32BufferAttribute(buf.conf, 1));
    geo.computeVertexNormals();
    geo.computeBoundingSphere();
    const mat = new THREE.MeshStandardMaterial({
      color: new THREE.Color(c.colour), roughness: 1.0, metalness: 0.0,
      polygonOffset: true, polygonOffsetFactor: c.offset, polygonOffsetUnits: c.offset * 4,
    });
    mat.name = `street-grid-${cls}`;
    confidence?.patch(mat);
    mat.customProgramCacheKey = () => `chicago4d-street-grid-${cls}`;
    const mesh = new THREE.Mesh(geo, mat);
    mesh.name = `street-grid-${cls}`;
    mesh.userData.cls = cls;
    mesh.castShadow = false;
    mesh.receiveShadow = true;
    group.add(mesh);
    meshes.push(mesh);
    materials.push(mat);
    out.census.triangles += buf.pos.length / 9;
  }

  // The parcel lines, draped every LOT_LINE_STEP_M along each edge.
  const linePos = [];
  for (const p of grid.parcels ?? []) {
    const poly = p.polygon_local_m;
    for (let i = 0; i < poly.length; i += 1) {
      const [e0, n0] = poly[i]; const [e1, n1] = poly[(i + 1) % poly.length];
      const L = Math.hypot(e1 - e0, n1 - n0);
      const k = Math.max(1, Math.ceil(L / LOT_LINE_STEP_M));
      for (let j = 0; j < k; j += 1) {
        const ea = e0 + ((e1 - e0) * j) / k; const na = n0 + ((n1 - n0) * j) / k;
        const eb = e0 + ((e1 - e0) * (j + 1)) / k; const nb = n0 + ((n1 - n0) * (j + 1)) / k;
        linePos.push(wx(ea), terrain.surfaceHeight(ea, na) + LOT_LINE_LIFT_M, wz(na),
          wx(eb), terrain.surfaceHeight(eb, nb) + LOT_LINE_LIFT_M, wz(nb));
      }
    }
    out.census.parcels += 1;
  }
  let lineGeo = null; let lineMat = null;
  if (linePos.length) {
    lineGeo = new THREE.BufferGeometry();
    lineGeo.setAttribute('position', new THREE.Float32BufferAttribute(linePos, 3));
    lineGeo.computeBoundingSphere();
    lineMat = new THREE.LineBasicMaterial({ color: 0x4a4540, transparent: true, opacity: 0.7 });
    lineMat.name = 'street-grid-lot-lines';
    const lines = new THREE.LineSegments(lineGeo, lineMat);
    lines.name = 'street-grid-lot-lines';
    group.add(lines);
  }
  group.userData.census = out.census;

  const faceById = new Map((grid.faces ?? []).map((f) => [f.id, f]));
  const wayById = new Map([
    ...(grid.carriageways ?? []).map((c) => [c.id, ['carriageway', c]]),
    ...(grid.alleys ?? []).map((a) => [a.id, ['alley', a]]),
  ]);

  /** The parcel standing at a plan point, if any. */
  out.parcelAt = (e, n) => (grid.parcels ?? []).find((p) => pointInPolygon(e, n, p.polygon_local_m)) ?? null;

  const raycaster = new THREE.Raycaster();
  /** What is under the crosshair: a band, a roadway, an alley, or the lot the ray
   *  meets the ground on. Answers with the grid's own card record. */
  out.pickAt = (ndc, camera) => {
    if (!camera) return null;
    raycaster.setFromCamera(ndc ?? new THREE.Vector2(0, 0), camera);
    raycaster.far = Math.max(400, camera.position.y * 4);
    const hits = raycaster.intersectObjects(meshes, false);
    if (hits.length) {
      const hit = hits[0];
      const cls = hit.object.userData.cls;
      const span = (spans[cls] ?? []).find((s) => hit.faceIndex >= s.from && hit.faceIndex < s.to);
      if (span) {
        let record = null;
        if (span.id.includes('|')) {
          const [fid, band] = span.id.split('|');
          record = bandCard(faceById.get(fid), band, grid);
        } else {
          const [kind, rec] = wayById.get(span.id) ?? [];
          if (rec) record = wayCard(kind, rec, grid);
        }
        if (record) return { id: record.id, record, point: hit.point.clone(), distance: hit.distance };
      }
    }
    // No band or roadway: march the ray to the ground and ask which lot it lands in.
    const o = raycaster.ray.origin; const d = raycaster.ray.direction;
    for (let t = 0.5; t < raycaster.far; t += 0.5) {
      const x = o.x + d.x * t; const y = o.y + d.y * t; const z = o.z + d.z * t;
      const e = x; const n = -z;
      if (y <= terrain.surfaceHeight(e, n)) {
        const p = out.parcelAt(e, n);
        if (!p) return null;
        const record = parcelCard(p, grid);
        return { id: p.id, record, point: new THREE.Vector3(x, y, z), distance: t };
      }
    }
    return null;
  };

  out.dispose = () => {
    for (const m of meshes) m.geometry.dispose();
    for (const m of materials) m.dispose();
    lineGeo?.dispose(); lineMat?.dispose();
  };
  return out;
}
