/**
 * street-grid.js — the 1904 Prairie Avenue street, alley and parcel grid (T-0474),
 * draped on the scene's own heightfield, and paved in its period materials (T-1728).
 *
 * WHAT IT DRAWS, from `data/street_grid/<scene>.json` (generated by
 * tools/trace_prairie_1904_grid.py from the Sanborn 1911 sheets 20, 28 and 35):
 *
 *   carriageways   curb line to curb line, one polygon per street segment
 *   faces          the four bands of every block's sidewalk space, measured from
 *                  the street line: a 1-ft margin, the walk, the parkway, the curb
 *   alleys         at their drawn widths
 *   parcels        as lines: the lots on both faces of Prairie Avenue, and (T-2116) the
 *                  Indiana and Calumet frontage lots and the cross-street corners
 *
 * WHAT IT PAVES THEM WITH, from `data/street_surfaces/<scene>.json` (T-1728,
 * authored, held to the grid and the sources by tools/check_street_surfaces.py):
 * every carriageway, alley and band names a material, a tier, its sources and a
 * date range the scene date falls in. Prairie Avenue 16th-20th is the 1903 sheet
 * asphalt two city records either side of the scene date name; 20th-22nd and the
 * cross streets are the worn macadam the city's December 1904 repair survey
 * lists; the walks, curbs and parkways are reconstructed (docs/LIBERTIES.md L296,
 * L297). The materials are the procedural library `assets/textures/prairie_1904_pbr/`
 * — a colour, a normal and a packed ORM map each, read at the metric tile its
 * material.json states, so a walk block is five feet long because the 1905 code
 * says so and not because it looked right. The pictures are evidence of nothing;
 * the file that says which surface wears which picture is the evidence.
 *
 * Still no level: the bands lie on the ground the heightfield already has (a few
 * centimetres above it, so they win the depth test), with no curb reveal and no
 * crown, because no source read so far gives either (L293).
 *
 * WHAT IT SHARES WITH EVERY OTHER DERIVED LAYER. A scene that does not list
 * `street_grid` hands this no data base and it draws nothing (T-1739's layer
 * contract), so the 1835 town is untouched. A failed fetch degrades to nothing
 * drawn plus a recorded problem, never to an invented street; a surfaces file or a
 * texture that does not arrive degrades to flat tones plus a problem. Every vertex
 * carries `_confidence` at the LOWER of its band's geometry tier and its
 * material's tier, so hiding `reconstructed` takes away every surface whose look is
 * ours. A pick opens a card built from the two files' own records.
 */

import * as THREE from 'three';

/** Longest triangle edge after draping, metres. The heightfield's cell is 2.5 m,
 *  so a triangle no longer than that cannot bridge a cell and float or sink. */
const MAX_EDGE_M = 2.5;
const LEVEL = { attested: 0, inferred: 0.5, reconstructed: 1 };
const FT = 0.3048;
const LIBRARY = 'textures/prairie_1904_pbr/';

/**
 * The draw order is the stacking order: each class a few centimetres above the one
 * it overlaps, plus a polygon offset, so a band laid over a carriageway (the
 * carriageways run through their intersections and under the corner bands) always
 * wins. A carriageway also rises by its `priority` (street_surfaces), so where two
 * roadways cross the avenue's surface is drawn over the cross street's (L297).
 * `colour` is the flat tone a surface falls back to when its maps do not arrive.
 */
const CLASSES = {
  carriageway: { lift: 0.03, colour: 0x7a7066, offset: -8, tier: 'inferred' },
  alley: { lift: 0.035, colour: 0x857a6c, offset: -9, tier: 'inferred' },
  margin: { lift: 0.05, colour: 0x7c8a66, offset: -10, tier: 'inferred' },
  parkway: { lift: 0.05, colour: 0x7c8a66, offset: -10, tier: 'reconstructed' },
  walk: { lift: 0.055, colour: 0xc2bdb2, offset: -11, tier: 'reconstructed' },
  curb: { lift: 0.06, colour: 0xd9d5cc, offset: -12, tier: 'reconstructed' },
};
const PRIORITY_LIFT_M = 0.003;
const LOT_LINE_LIFT_M = 0.09;
const LOT_LINE_STEP_M = 2.0;

const wx = (e) => e;
const wz = (n) => -n;
const worse = (a, b) => ((LEVEL[a] ?? 1) >= (LEVEL[b] ?? 1) ? a : b);

async function getJSON(url) {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.json();
}

/* -------------------------------------------------------------------------- */
/* geometry                                                                    */
/* -------------------------------------------------------------------------- */

const sub = (p, q) => [p[0] - q[0], p[1] - q[1]];
const dot = (p, q) => p[0] * q[0] + p[1] * q[1];
const lerp = (p, q, f) => [p[0] + (q[0] - p[0]) * f, p[1] + (q[1] - p[1]) * f];
const len = (p) => Math.hypot(p[0], p[1]);

/**
 * A quad as the grid writes it — a, b along one side and d, c along the other —
 * relabelled so that a->b runs ALONG the street, with a metric frame: `t` along,
 * `n` across towards d. A multi-quad record (a curve cut every 5 m) steps along
 * a->b already; a single quad is along its longer side, which is how a cross
 * street's one quad (written across-first) comes out right.
 */
function framed(q, alongIsAB) {
  let [a, b, c, d] = q;
  if (!alongIsAB) [b, d] = [d, b];
  const ab = sub(b, a);
  const L = len(ab) || 1;
  const t = [ab[0] / L, ab[1] / L];
  let n = [-t[1], t[0]];
  if (dot(n, sub(d, a)) < 0) n = [-n[0], -n[1]];
  return { a, b, c, d, t, n, along: L };
}

/**
 * The framed quad to plan triangles on a grid no coarser than MAX_EDGE_M either
 * way, by bilinear interpolation, each vertex carrying its metric (along, across)
 * position in the record's frame. So a strip 15 cm wide costs two triangles per
 * 2.5 m of its length, not the hundreds an isotropic subdivision spends on a sliver.
 */
function quadTriangles(f, origin, offset) {
  const { a, b, c, d } = f;
  const along = Math.max(len(sub(b, a)), len(sub(c, d)));
  const across = Math.max(len(sub(d, a)), len(sub(c, b)));
  const nu = Math.max(1, Math.ceil(along / MAX_EDGE_M));
  const nv = Math.max(1, Math.ceil(across / MAX_EDGE_M));
  const ccw = (b[0] - a[0]) * (d[1] - a[1]) - (b[1] - a[1]) * (d[0] - a[0]) >= 0;
  const at = (u, v) => {
    const p = lerp(lerp(a, b, u), lerp(d, c, u), v);
    const r = sub(p, origin);
    return [p[0], p[1], offset + dot(r, f.t), dot(r, f.n)];
  };
  const out = [];
  for (let i = 0; i < nu; i += 1) {
    for (let j = 0; j < nv; j += 1) {
      const p00 = at(i / nu, j / nv); const p10 = at((i + 1) / nu, j / nv);
      const p11 = at((i + 1) / nu, (j + 1) / nv); const p01 = at(i / nu, (j + 1) / nv);
      // counter-clockwise in plan, so the normals point up
      if (ccw) out.push([p00, p10, p11], [p00, p11, p01]);
      else out.push([p00, p11, p10], [p00, p01, p11]);
    }
  }
  return out;
}

function pointInPolygon(e, n, poly) {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i, i += 1) {
    const [xi, yi] = poly[i]; const [xj, yj] = poly[j];
    if ((yi > n) !== (yj > n) && e < ((xj - xi) * (n - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

function ftm(ft) { return `${ft} ft (${(ft * 0.3048).toFixed(2)} m)`; }

/* -------------------------------------------------------------------------- */
/* the surfaces                                                                */
/* -------------------------------------------------------------------------- */

/** The texture library: one entry per material the surfaces file names. */
async function loadLibrary(assetBase, surfaces) {
  const loader = new THREE.TextureLoader();
  const base = new URL(LIBRARY, assetBase);
  const out = new Map();
  const tex = async (url, srgb) => {
    const t = await loader.loadAsync(url);
    t.wrapS = THREE.RepeatWrapping;
    t.wrapT = THREE.RepeatWrapping;
    // The colour map is sRGB; the normal and the packed ORM are data (material.json
    // records both as linear), and a gamma curve on a normal bends it.
    t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    // A street is seen at a grazing angle from 1.6 m; without anisotropy its
    // joints turn to mush ten metres out (the roof relief uses the same 8).
    t.anisotropy = 8;
    return t;
  };
  await Promise.all(Object.entries(surfaces.materials ?? {}).map(async ([id, m]) => {
    const here = new URL(`${m.texture}/`, base);
    const sheet = await getJSON(new URL('material.json', here));
    const along = Number(sheet.span_along_m ?? sheet.span_m);
    if (!(along > 0)) throw new Error(`${m.texture}: material.json states no span`);
    const [map, normalMap, orm] = await Promise.all([
      tex(new URL(sheet.web.basecolor, here).href, true),
      tex(new URL(sheet.web.normal_gl, here).href, false),
      tex(new URL(sheet.web.orm, here).href, false),
    ]);
    out.set(id, { map, normalMap, orm, along, across: sheet.span_across_m, sheet });
  }));
  return out;
}

/** The surface a carriageway, alley or band wears, with the piece index if split. */
function surfaceOf(surfaces, kind, id, band = null, face = null) {
  if (!surfaces) return null;
  if (kind === 'carriageway') return surfaces.carriageways?.[id] ?? null;
  if (kind === 'alley') return surfaces.alleys?.[id] ?? null;
  return surfaces.faces?.[face]?.[band] ?? surfaces.bands?.[band] ?? null;
}

/** A card attribute for the surface, in the surfaces file's own words. */
function materialAttribute(surfaces, s) {
  if (!s) {
    return {
      value: 'not claimed', confidence: 'reconstructed', sources: [],
      note: 'No surface is recorded for this piece of the grid; it is drawn in a neutral tone.',
    };
  }
  const m = surfaces?.materials?.[s.material] ?? {};
  const range = s.exists ? ` In place ${s.exists.from} to ${s.exists.to}: ${s.exists.from_basis}; ${s.exists.to_basis}.` : '';
  return {
    value: m.name ?? s.material,
    confidence: s.tier,
    sources: s.sources ?? [],
    note: `${s.note ?? ''}${range}${s.liberty ? ` ${s.liberty}.` : ''}`.trim(),
  };
}

/* -------------------------------------------------------------------------- */
/* the cards                                                                   */
/* -------------------------------------------------------------------------- */

function parcelCard(p, grid) {
  const sheet = (p.sources ?? [])[0] ?? '';
  const addr = p.addresses_1911?.length ? p.addresses_1911.join(', ') : null;
  // T-2116: the Indiana, Calumet and cross-street lots carry their own street.
  const streetName = grid.streets?.[p.street]?.name_1904 ?? 'Prairie Avenue';
  const onPrairie = (p.street ?? 'prairie') === 'prairie';
  const cross = p.cross_street_addresses_1911 ?? [];
  const ruling = p.id === grid.rulings?.glessner_lot_frontage?.parcel ? grid.rulings.glessner_lot_frontage : null;
  const attributes = {
    frontage_ft: {
      value: p.frontage_ft, confidence: ruling ? ruling.tier : p.geometry_tier,
      sources: ruling ? ruling.sources : p.sources,
      note: ruling ? `${ruling.reading} ${ruling.why_not_77} ${ruling.why_not_74}` : p.read,
    },
    depth_ft: { value: p.depth_ft, confidence: p.geometry_tier, sources: p.sources, note: p.read },
    addresses_printed_1911: {
      value: addr ?? 'none printed', confidence: 'inferred', sources: [sheet],
      note: 'The numbers the 1911 sheet prints beside this lot. Chicago renumbered its streets in 1909-11, '
        + (onPrairie
          ? 'so a 1911 number is a cross-reference to the Prairie library, not a claim about the 1904 address'
          : 'so a 1911 number is not a claim about the 1904 address')
        + (p.library_disagreements?.length ? `. ${p.library_disagreements.map((d) => d.reading).join(' ')}` : '.'),
    },
    ...(cross.length ? {
      cross_street_addresses_1911: {
        value: cross.join(', '), confidence: 'inferred', sources: [sheet],
        note: 'Numbers the 1911 sheet prints on this lot\'s cross-street side, with no lot line drawn to part them from it.',
      },
    } : {}),
    street_face: { value: p.street_face, confidence: 'inferred', sources: p.sources, note: 'The block face this lot fronts, as laid out in the grid.' },
  };
  // T-1745: the legal lot, as Robinson's 1886 atlas (16th-18th) or HABS (1800) names it.
  const legal = p.legal_lots;
  if (legal) {
    attributes.legal_lots = {
      value: legal.label, confidence: legal.tier, sources: legal.sources ?? [], note: legal.note ?? '',
    };
  }
  const legalWords = legal?.lots?.length
    ? ` ${legal.tier === 'attested' ? 'HABS\'s legal description' : "Robinson's 1886 atlas"} names it `
      + `${legal.label.charAt(0).toLowerCase()}${legal.label.slice(1)}${legal.label.endsWith('.') ? '' : '.'}`
    : '';
  return {
    id: p.id,
    sidecar: {
      name: addr ? `${p.addresses_1911[0].split(' ')[0]} ${streetName} — the lot` : `A lot on ${streetName}`,
      phase: null,
      // The card's opening line, in the grid's own words (popup.js prints it in
      // place of the sentence it composes for a building).
      change_note: `A lot on ${p.where}: ${p.frontage_ft} ft along the ${(p.street ?? 'prairie').startsWith('e') ? 'street' : 'avenue'} and ${p.depth_ft} ft deep, `
        + `as the 1911 Sanborn sheet draws it${addr ? `, printed ${addr}` : ', with no number printed'}.`
        + `${legalWords} No building is drawn on it yet.`,
      placement: {
        symbolic_location: p.where ?? streetName,
        position_confidence: p.geometry_tier,
        position_sources: p.sources,
        position_note: `${p.read}. A 1911 survey carried to 1904: the lot lines are assumed unchanged between the two dates.`,
      },
      attributes,
      citations: [],
      research_doc: 'docs/RESEARCH/prairie_1904_street_grid.md',
      research_note: `Parcel ${p.id} of the 1904 Prairie Avenue grid (data/street_grid/1904.json, `
        + `${onPrairie ? 'T-0474' : 'T-2116'})`
        + (p.library_frontage_ids?.length ? `; the Prairie library's frontage rows ${p.library_frontage_ids.join(', ')}` : '')
        + '. No building is drawn on it yet.'
        + (ruling ? ` ${ruling.for_T_1732 ?? ruling['for_T-1732'] ?? ''}` : ''),
    },
  };
}

function bandCard(face, band, grid, surfaces) {
  const street = grid.streets?.[face.street] ?? {};
  const xs = grid.cross_sections?.[face.cross_section] ?? {};
  const b = (xs.bands ?? []).find((x) => x.band === band) ?? {};
  const words = { margin: 'the margin inside the walk', walk: 'the walk', parkway: 'the parkway', curb: 'the curb' };
  const s = surfaceOf(surfaces, 'band', null, band, face.id);
  const mat = surfaces?.materials?.[s?.material]?.name;
  return {
    id: `${face.id}.${band}`,
    sidecar: {
      name: `${street.name_1904 ?? face.street} — ${words[band] ?? band}`,
      phase: null,
      change_note: `${(words[band] ?? band).replace(/^the /, 'The ')} along ${face.where}: `
        + `${Math.round((b.to_ft - b.from_ft) * 10) / 10} ft wide, ${b.from_ft} to ${b.to_ft} ft out from the property line`
        + (mat ? `, drawn as ${mat} (${s.tier}). ` : '. ')
        + (b.tier === 'reconstructed'
          ? 'The space it shares is the 1905 street code’s rule; this width is our reconstruction.'
          : 'This is the 1905 street code’s rule, carried to this block.'),
      placement: {
        symbolic_location: face.where ?? face.street,
        position_confidence: 'inferred',
        position_sources: grid.sources ?? [],
        position_note: `Measured from the street line read off ${face.street_line_from}.`,
      },
      attributes: {
        material: materialAttribute(surfaces, s),
        width: {
          value: ftm(Math.round((b.to_ft - b.from_ft) * 10) / 10), confidence: b.tier ?? 'reconstructed',
          sources: b.sources ?? [], note: b.note ?? '',
        },
        from_street_line: {
          value: `${b.from_ft} to ${b.to_ft} ft`, confidence: b.tier ?? 'reconstructed', sources: b.sources ?? [],
          note: 'Measured outward from the street (property) line into the street.',
        },
        sidewalk_space: {
          value: ftm(xs.sidewalk_space_ft?.value), confidence: xs.sidewalk_space_ft?.tier ?? 'inferred',
          sources: xs.sidewalk_space_ft?.sources ?? [], note: xs.sidewalk_space_ft?.note ?? '',
        },
      },
      citations: [],
      research_doc: 'docs/RESEARCH/prairie_1904_street_surfaces.md',
      research_note: `Street face ${face.id} of the 1904 Prairie Avenue grid (T-0474), paved by T-1728. ${street.width_note ?? ''}`,
    },
  };
}

function wayCard(kind, rec, grid, surfaces, piece) {
  const street = kind === 'carriageway' ? grid.streets?.[rec.street] ?? {} : {};
  const xs = grid.cross_sections?.[street.cross_section] ?? {};
  const whole = surfaceOf(surfaces, kind, rec.id);
  const s = piece != null && whole?.pieces ? whole.pieces[piece] : whole;
  const mat = surfaces?.materials?.[s?.material]?.name;
  const roadway = street.row_width_ft - 2 * (xs.sidewalk_space_ft?.value ?? 0);
  const attributes = kind === 'carriageway' ? {
    paving: materialAttribute(surfaces, s),
    street_width: { value: ftm(street.row_width_ft), confidence: street.row_width_tier ?? 'inferred', sources: street.row_width_sources ?? [], note: `Printed "${street.printed ?? ''}" on the 1911 sheets; ${street.width_note ?? ''}` },
    carriageway: {
      value: ftm(roadway), confidence: 'inferred',
      sources: rec.sources ?? [], note: `The street width less a ${xs.sidewalk_space_ft?.value}-ft sidewalk space on each side. ${xs.sidewalk_space_ft?.note ?? ''}`,
    },
    kept_by: surfaces?.authority ? {
      value: surfaces.authority.in_1904, confidence: 'attested', sources: surfaces.authority.sources ?? [],
      note: surfaces.authority.note ?? '',
    } : undefined,
  } : {
    surface: materialAttribute(surfaces, s),
    width: { value: `${rec.printed_width_ft} ft as printed`, confidence: 'inferred', sources: rec.sources ?? [], note: rec.note ?? 'Drawn at the width the sheet draws.' },
  };
  if (!attributes.kept_by) delete attributes.kept_by;
  return {
    id: piece != null ? `${rec.id}#${piece}` : rec.id,
    sidecar: {
      name: kind === 'carriageway' ? `${street.name_1904 ?? rec.street} — the roadway` : 'An alley',
      phase: null,
      change_note: kind === 'carriageway'
        ? `The roadway of ${rec.where}: ${mat ? `${mat} (${s.tier}), ` : ''}${roadway} ft between the curbs `
          + `in a ${street.row_width_ft}-ft street, as the 1911 sheets draw the street and the 1905 code divides it.`
        : `An alley ${rec.where}, ${rec.printed_width_ft} ft wide as the 1911 sheet prints it${mat ? `, drawn as ${mat} (${s.tier})` : ''}.`,
      placement: {
        symbolic_location: rec.where ?? rec.id,
        position_confidence: rec.geometry_tier ?? 'inferred',
        position_sources: rec.sources ?? [],
        position_note: `Between ${(rec.between ?? rec.drawn_from ?? []).join(' and ')}.`,
      },
      attributes,
      citations: [],
      research_doc: 'docs/RESEARCH/prairie_1904_street_surfaces.md',
      research_note: `${kind === 'carriageway' ? 'Carriageway' : 'Alley'} ${rec.id} of the 1904 Prairie Avenue grid (T-0474), paved by T-1728.`,
    },
  };
}

/* -------------------------------------------------------------------------- */
/* the layer                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * @param {object} o dataBase (data/ root, or null when the scene does not list the
 *                   layer) · assetBase (where textures/ lives) · sceneId · terrain ·
 *                   confidence · problems
 */
export async function createStreetGrid({
  dataBase, assetBase = null, sceneId, terrain, confidence = null, problems = [],
} = {}) {
  const group = new THREE.Group();
  group.name = 'street-grid';
  const out = {
    group,
    grid: null,
    surfaces: null,
    census: { carriageways: 0, faces: 0, alleys: 0, parcels: 0, triangles: 0, surfaced: 0, textured: 0 },
    parcelAt: () => null,
    pickAt: () => null,
    dispose: () => {},
  };
  if (!dataBase || !terrain) return out;
  let grid;
  try {
    grid = await getJSON(new URL(`street_grid/${sceneId}.json`, dataBase));
  } catch (err) {
    problems.push(`street grid: ${err.message} — no street is drawn`);
    return out;
  }
  out.grid = grid;

  // T-1728 — the materials. Either half failing leaves the grid drawn in flat tones.
  let surfaces = null;
  try {
    surfaces = await getJSON(new URL(`street_surfaces/${sceneId}.json`, dataBase));
  } catch (err) {
    problems.push(`street surfaces: ${err.message} — the streets are drawn in flat tones`);
  }
  out.surfaces = surfaces;
  let library = new Map();
  if (surfaces && assetBase) {
    try {
      library = await loadLibrary(assetBase, surfaces);
    } catch (err) {
      problems.push(`street surface maps not bound — ${err.message}`);
      library = new Map();
    }
  }

  /**
   * One buffer per (class, material, priority): a mesh is a single material, and
   * where two carriageways of different priority cross, the one above must be a
   * different draw so its lift wins. Seven carriageway groups, the alleys, the
   * turf, the walk and the curb — eleven meshes and the lot lines.
   */
  const bufs = new Map();
  const tierOf = {};
  for (const xs of Object.values(grid.cross_sections ?? {})) for (const b of xs.bands ?? []) tierOf[b.band] = b.tier;

  const bufFor = (cls, surface, priority) => {
    const c = CLASSES[cls];
    const shared = cls === 'margin' ? 'parkway' : cls;   // the foot and the parkway are one turf
    const key = `${shared}|${surface?.material ?? 'none'}|${priority}`;
    if (!bufs.has(key)) {
      bufs.set(key, {
        key, cls: shared, material: surface?.material ?? null, priority,
        lift: c.lift + priority * PRIORITY_LIFT_M, offset: c.offset - priority * 0.3,
        pos: [], uv: [], conf: [], spans: [],
      });
    }
    return bufs.get(key);
  };

  /**
   * Push one record's quads. `tile` is [along, across] in metres; across may be a
   * number (the band width, for a walk or a curb tile that spans its band) or null
   * for flat-tone surfaces with no maps.
   */
  const push = (cls, id, quads, geometryTier, surface, { priority = 0, tileAcross = null, tileAlong = null, pieceOf = null } = {}) => {
    const buf = bufFor(cls, surface, priority);
    const lib = surface ? library.get(surface.material) : null;
    const along = tileAlong ?? lib?.along ?? 4;
    const across = tileAcross ?? (typeof lib?.across === 'number' ? lib.across : along);
    const level = LEVEL[worse(geometryTier ?? CLASSES[cls].tier, surface?.tier ?? 'reconstructed')] ?? 1;
    const from = buf.pos.length / 9;
    const alongIsAB = (pieceOf ? true : quads.length > 1);
    // A tile with no direction (asphalt, macadam, cinders, turf) is laid in WORLD metres on
    // the world axis nearest the street's own, so two segments of one street that
    // overlap through an intersection draw the same texel in the same place
    // instead of two grains fighting, and its wheel streaks still run within a
    // degree of the street. A `directional` tile (walk blocks, curbstones, brick
    // courses; its material.json says so) follows the record's own frame.
    const worldLaid = !lib || !lib.sheet.directional;
    let offset = 0;
    for (const q of quads) {
      const f = framed(q, alongIsAB || len(sub(q[1], q[0])) >= len(sub(q[3], q[0])));
      const origin = pieceOf?.origin ?? f.a;
      const frame = pieceOf ? { ...f, t: pieceOf.t, n: pieceOf.n } : f;
      const northSouth = Math.abs(frame.t[1]) > Math.abs(frame.t[0]);
      for (const tri of quadTriangles(frame, origin, pieceOf ? 0 : offset)) {
        for (const [e, n, u, v] of tri) {
          buf.pos.push(wx(e), terrain.surfaceHeight(e, n) + buf.lift, wz(n));
          if (worldLaid) buf.uv.push((northSouth ? n : e) / along, (northSouth ? e : n) / along);
          else buf.uv.push(u / along, v / across);
          buf.conf.push(level);
        }
      }
      offset += f.along;
    }
    buf.spans.push({ id, from, to: buf.pos.length / 9 });
  };

  const carriageById = new Map((grid.carriageways ?? []).map((c) => [c.id, c]));
  const centroid = (rec) => {
    const q = (rec?.quads_local_m ?? [])[0];
    if (!q) return null;
    return [(q[0][0] + q[1][0] + q[2][0] + q[3][0]) / 4, (q[0][1] + q[1][1] + q[2][1] + q[3][1]) / 4];
  };

  for (const c of grid.carriageways ?? []) {
    const s = surfaceOf(surfaces, 'carriageway', c.id);
    const quads = c.quads_local_m ?? [];
    const priority = s?.priority ?? 0;
    if (s?.pieces?.length && quads.length === 1) {
      // A segment whose surface changes at a cross street (Calumet at 21st): cut
      // the one quad where the cross street's centre falls along it.
      const q = quads[0];
      const f = framed(q, len(sub(q[1], q[0])) >= len(sub(q[3], q[0])));
      let lo = 0;
      s.pieces.forEach((piece, i) => {
        let hi = 1;
        if (piece.until) {
          const cen = centroid(carriageById.get(piece.until));
          hi = cen ? Math.min(1, Math.max(lo, dot(sub(cen, f.a), f.t) / f.along)) : 1;
        }
        const cut = [lerp(f.a, f.b, lo), lerp(f.a, f.b, hi), lerp(f.d, f.c, hi), lerp(f.d, f.c, lo)];
        push('carriageway', `${c.id}#${i}`, [cut], c.geometry_tier, piece,
          { priority, pieceOf: { origin: f.a, t: f.t, n: f.n } });
        lo = hi;
      });
      out.census.surfaced += 1;
    } else {
      push('carriageway', c.id, quads, c.geometry_tier, s, { priority });
      if (s) out.census.surfaced += 1;
    }
    out.census.carriageways += 1;
  }
  for (const a of grid.alleys ?? []) {
    const s = surfaceOf(surfaces, 'alley', a.id);
    push('alley', a.id, a.quads_local_m ?? [], a.geometry_tier, s);
    if (s) out.census.surfaced += 1;
    out.census.alleys += 1;
  }
  for (const f of grid.faces ?? []) {
    const xs = grid.cross_sections?.[f.cross_section] ?? {};
    for (const [band, quads] of Object.entries(f.bands ?? {})) {
      if (!CLASSES[band]) continue;
      const s = surfaceOf(surfaces, 'band', null, band, f.id);
      const b = (xs.bands ?? []).find((x) => x.band === band);
      const width = b ? (b.to_ft - b.from_ft) * FT : null;
      const lib = s ? library.get(s.material) : null;
      let tileAlong = null;
      // A walk is laid out in the code's 5 x 6 ft blocks (sec. 2062), the long side
      // across a 6-ft walk and along a 5-ft one; the tile holds two blocks along.
      const blocks = s?.blocks?.[f.cross_section];
      if (blocks) tileAlong = 2 * blocks.along_ft * FT;
      push(band, `${f.id}|${band}`, quads, tierOf[band], s,
        { tileAcross: lib?.across === 'band' ? width : null, tileAlong });
      if (s) out.census.surfaced += 1;
    }
    out.census.faces += 1;
  }

  const meshes = [];
  const materials = [];
  for (const buf of bufs.values()) {
    const c = CLASSES[buf.cls];
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(buf.pos, 3));
    geo.setAttribute('uv', new THREE.Float32BufferAttribute(buf.uv, 2));
    geo.setAttribute('_confidence', new THREE.Float32BufferAttribute(buf.conf, 1));
    geo.computeVertexNormals();
    geo.computeBoundingSphere();
    const lib = buf.material ? library.get(buf.material) : null;
    const mat = new THREE.MeshStandardMaterial({
      color: lib ? 0xffffff : new THREE.Color(c.colour), roughness: 1.0, metalness: 0.0,
      // T-1805: these surfaces already stand 30–60 mm above the sampled
      // terrain, with priority expressed in their actual lift. A large negative
      // slope bias (-11 for walks) pulls a grazing sidewalk THROUGH nearby walls,
      // producing the apparent projecting slab at Glessner's corner. Retain only
      // a one-unit numerical tie-break; do not displace depth by screen-space slope.
      polygonOffset: true, polygonOffsetFactor: 0, polygonOffsetUnits: -1,
    });
    if (lib) {
      mat.map = lib.map;
      mat.normalMap = lib.normalMap;
      // One file in two slots, as the roof relief does: ORM is R=AO, G=roughness.
      mat.roughnessMap = lib.orm;
      mat.aoMap = lib.orm;
      mat.aoMapIntensity = 0.6;
      mat.normalScale = new THREE.Vector2(0.8, 0.8);
      out.census.textured += 1;
    }
    mat.name = `street-grid-${buf.cls}${buf.material ? `-${buf.material}` : ''}`;
    confidence?.patch(mat);
    mat.customProgramCacheKey = () => `chicago4d-street-grid-${lib ? 'mapped' : 'flat'}`;
    const mesh = new THREE.Mesh(geo, mat);
    mesh.name = `street-grid-${buf.cls}${buf.material ? `-${buf.material}` : ''}${buf.priority ? `-p${buf.priority}` : ''}`;
    mesh.userData.cls = buf.cls;
    mesh.userData.material = buf.material;
    mesh.userData.spans = buf.spans;
    mesh.castShadow = false;
    mesh.receiveShadow = true;
    group.add(mesh);
    meshes.push(mesh);
    materials.push(mat);
    out.census.triangles += buf.pos.length / 9;
  }

  // The parcel lines, draped every LOT_LINE_STEP_M along each edge.
  const linePos = [];
  for (const p of grid.parcels ?? []) {
    const poly = p.polygon_local_m;
    for (let i = 0; i < poly.length; i += 1) {
      const [e0, n0] = poly[i]; const [e1, n1] = poly[(i + 1) % poly.length];
      const L = Math.hypot(e1 - e0, n1 - n0);
      const k = Math.max(1, Math.ceil(L / LOT_LINE_STEP_M));
      for (let j = 0; j < k; j += 1) {
        const ea = e0 + ((e1 - e0) * j) / k; const na = n0 + ((n1 - n0) * j) / k;
        const eb = e0 + ((e1 - e0) * (j + 1)) / k; const nb = n0 + ((n1 - n0) * (j + 1)) / k;
        linePos.push(wx(ea), terrain.surfaceHeight(ea, na) + LOT_LINE_LIFT_M, wz(na),
          wx(eb), terrain.surfaceHeight(eb, nb) + LOT_LINE_LIFT_M, wz(nb));
      }
    }
    out.census.parcels += 1;
  }
  let lineGeo = null; let lineMat = null;
  if (linePos.length) {
    lineGeo = new THREE.BufferGeometry();
    lineGeo.setAttribute('position', new THREE.Float32BufferAttribute(linePos, 3));
    lineGeo.computeBoundingSphere();
    lineMat = new THREE.LineBasicMaterial({ color: 0x4a4540, transparent: true, opacity: 0.7 });
    lineMat.name = 'street-grid-lot-lines';
    const lines = new THREE.LineSegments(lineGeo, lineMat);
    lines.name = 'street-grid-lot-lines';
    group.add(lines);
  }
  group.userData.census = out.census;

  const faceById = new Map((grid.faces ?? []).map((f) => [f.id, f]));
  const wayById = new Map([
    ...(grid.carriageways ?? []).map((c) => [c.id, ['carriageway', c]]),
    ...(grid.alleys ?? []).map((a) => [a.id, ['alley', a]]),
  ]);

  /** The card a span answers with — a band, a roadway (or one piece of it), an alley. */
  const cardFor = (spanId) => {
    if (spanId.includes('|')) {
      const [fid, band] = spanId.split('|');
      const face = faceById.get(fid);
      return face ? bandCard(face, band, grid, surfaces) : null;
    }
    const [rid, piece] = spanId.split('#');
    const [kind, rec] = wayById.get(rid) ?? [];
    return rec ? wayCard(kind, rec, grid, surfaces, piece != null ? Number(piece) : null) : null;
  };
  out.cardFor = cardFor;

  /** The parcel standing at a plan point, if any. */
  out.parcelAt = (e, n) => (grid.parcels ?? []).find((p) => pointInPolygon(e, n, p.polygon_local_m)) ?? null;

  const raycaster = new THREE.Raycaster();
  /** What is under the crosshair: a band, a roadway, an alley, or the lot the ray
   *  meets the ground on. Answers with the grid's own card record. */
  out.pickAt = (ndc, camera) => {
    if (!camera) return null;
    raycaster.setFromCamera(ndc ?? new THREE.Vector2(0, 0), camera);
    raycaster.far = Math.max(400, camera.position.y * 4);
    const hits = raycaster.intersectObjects(meshes, false);
    if (hits.length) {
      const hit = hits[0];
      const span = (hit.object.userData.spans ?? []).find((s) => hit.faceIndex >= s.from && hit.faceIndex < s.to);
      const record = span ? cardFor(span.id) : null;
      if (record) return { id: record.id, record, point: hit.point.clone(), distance: hit.distance };
    }
    // No band or roadway: march the ray to the ground and ask which lot it lands in.
    const o = raycaster.ray.origin; const d = raycaster.ray.direction;
    for (let t = 0.5; t < raycaster.far; t += 0.5) {
      const x = o.x + d.x * t; const y = o.y + d.y * t; const z = o.z + d.z * t;
      const e = x; const n = -z;
      if (y <= terrain.surfaceHeight(e, n)) {
        const p = out.parcelAt(e, n);
        if (!p) return null;
        const record = parcelCard(p, grid);
        return { id: p.id, record, point: new THREE.Vector3(x, y, z), distance: t };
      }
    }
    return null;
  };

  out.dispose = () => {
    for (const m of meshes) m.geometry.dispose();
    for (const m of materials) m.dispose();
    for (const lib of library.values()) { lib.map.dispose(); lib.normalMap.dispose(); lib.orm.dispose(); }
    lineGeo?.dispose(); lineMat?.dispose();
  };
  return out;
}
