#!/usr/bin/env python3
"""Tie the image store (kevinrhaas/chicago-images) to the records that cite its files.

    python3 tools/sync_image_store.py            # write both manifests
    python3 tools/sync_image_store.py --check    # report only; exit 1 on a missing file

The bytes of the Prairie image collection live in kevinrhaas/chicago-images under
prairie-1904/files/, served by that repository's Pages site (owner, 2026-10-02). Records here
keep the LOGICAL path research/images/files/<name>; this tool writes:

  <store>/../MANIFEST.json      every file -> its record, title, source URLs, rights, sha256, bytes,
                                so the store is never a pile of unsourced pictures;
  research/images/STORE.json    the image host's base URL and every file's sha256 and bytes —
                                what build_images.py validates against and the viewer reads, so
                                neither needs the store cloned.

It reports files no record cites (orphans: never deleted by this tool) and files a record cites
that the store lacks (missing: an error under --check).
"""
from pathlib import Path
import hashlib, json, os, sys, time

P = Path(__file__).resolve().parents[1]
REPO = P.parents[1]
STORE = Path(os.environ.get('PRAIRIE_IMAGE_STORE') or (REPO.parent / 'chicago-images' / 'prairie-1904' / 'files'))
BASE_URL = 'https://kevinrhaas.github.io/chicago-images/prairie-1904/files/'
PREFIX = 'research/images/files/'
STORE_JSON = P / 'research/images/STORE.json'


def records():
    import glob
    out = {}
    for f in sorted(glob.glob(str(P / 'research/images/stream-*.json'))):
        for r in json.loads(Path(f).read_text()):
            for k in ('display', 'thumb'):
                v = (r.get('local') or {}).get(k)
                if v and v.startswith(PREFIX):
                    out[v[len(PREFIX):]] = r
    return out


def main():
    check = '--check' in sys.argv
    if not STORE.is_dir():
        sys.exit(f'image store not found at {STORE} — clone kevinrhaas/chicago-images beside this repository or set PRAIRIE_IMAGE_STORE')
    cited = records()
    files = {p.name: p for p in sorted(STORE.glob('*.jpg'))}
    missing = sorted(set(cited) - set(files))
    orphans = sorted(set(files) - set(cited))
    entries, store = {}, {}
    for name, p in files.items():
        b = p.read_bytes(); sha = hashlib.sha256(b).hexdigest()
        store[name] = {'bytes': len(b), 'sha256': sha}
        r = cited.get(name)
        entries[name] = {'bytes': len(b), 'sha256': sha, 'record': r and r['id'], 'title': r and r.get('title'),
                         'catalog_url': r and r.get('catalog_url'), 'image_url': r and r.get('image_url'),
                         'fetched_from': r and (r.get('local') or {}).get('fetched_from'),
                         'rights': r and r.get('rights'), 'rights_basis': r and r.get('rights_basis'),
                         'repository': r and r.get('repository')}
    total = sum(v['bytes'] for v in store.values())
    print(f'{len(files)} files, {total / 1048576:.1f} MB in the store; {len(cited)} cited by records; '
          f'{len(missing)} missing, {len(orphans)} orphan(s)')
    for n in missing[:20]: print('  MISSING', n)
    for n in orphans[:20]: print('  orphan ', n)
    if check:
        sys.exit(1 if missing else 0)
    manifest = {'_doc': 'GENERATED by kevinrhaas/chicago chicago/prairie_1904_v1/tools/sync_image_store.py. Every file '
                        'here belongs to a record in that repository (research/images/stream-*.json), which holds its '
                        'full description and provenance. Only public-domain / no-known-restrictions items are stored.',
                'generated': time.strftime('%Y-%m-%d'), 'files': entries}
    (STORE.parent / 'MANIFEST.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=1) + '\n')
    STORE_JSON.write_text(json.dumps({'_doc': 'GENERATED by tools/sync_image_store.py — the image store '
                                              '(kevinrhaas/chicago-images) as of its last sync: base URL and every file.',
                                      'base_url': BASE_URL, 'prefix': PREFIX, 'repository': 'kevinrhaas/chicago-images',
                                      'bytes': total, 'files': store}, indent=1) + '\n')
    print('wrote', STORE.parent / 'MANIFEST.json', 'and', STORE_JSON.relative_to(P))


if __name__ == '__main__':
    main()
